SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE role RESTART IDENTITY;
TRUNCATE TABLE user RESTART IDENTITY;
TRUNCATE TABLE account_type RESTART IDENTITY;
TRUNCATE TABLE account RESTART IDENTITY;
TRUNCATE TABLE transaction_type RESTART IDENTITY;
TRUNCATE TABLE transaction RESTART IDENTITY;
TRUNCATE TABLE token RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
