version: "3.7"
services:
  API:
    build: .
    image: my-atm-app
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/atm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Hello2you2!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  PostgreSQL:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=atm
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Hello2you2!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local